apiVersion: v2
appVersion: 0.4.0
description: TRMNL home screen app
name: trmnl-home-screen
version: 0.1.0
maintainers:
  - name: jvalskis
    url: https://github.com/jvalskis
dependencies:
  - name: common
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts
